version: '3'

services:
  minio:
    image: minio/minio
    volumes:
      - ./minio/data:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /export

  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"

  icecast:
    build: ./icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=icejdplayer
      - ICECAST_ADMIN_PASSWORD=icejdplayer
      - ICECAST_RELAY_PASSWORD=icejdplayer
      - ICECAST_MAX_CLIENTS=1000
      - ICECAST_MAX_SOURCES=1000
    ports:
      - 8000:8000

#  celery-worker:
#    build:
#      context: celery
#      dockerfile: dockerfile
#    volumes:
#      - ../web_server:/app
#    links:
#      - rabbit
#    depends_on:
#      - rabbit

