"""add binary_name to track

Revision ID: 415239fe4ebd
Revises: fde373abb825
Create Date: 2019-02-03 02:10:49.723373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415239fe4ebd'
down_revision = 'fde373abb825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('binary_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'binary_name')
    # ### end Alembic commands ###
