"""change security model

Revision ID: e31d3631d751
Revises: d210c7a223b6
Create Date: 2019-02-02 02:33:54.119038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31d3631d751'
down_revision = 'd210c7a223b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('security_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('users', sa.Column('source', sa.Enum('security', 'google', name='usersource'), server_default='security', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source')
    op.drop_table('security_users')
    op.drop_table('google_users')
    # ### end Alembic commands ###
